#Copyright (C) 2020-2021  Burak Martin (see 'AUTHOR' for full notice)

newActionName = "New Project.."
openActionName = "Open Project.."
saveActionName =  "Save"
saveAsActionName =  "Save as.."
quitActionName = "Quit"
scaleActionName = "Scale"
undoActionName = "Undo"
redoActionName = "Redo"
clearTrimapAction = "Trimap"
clearNewBackgroundActionName = "New Background"
zoomInActionName = "Zoom In"
zoomOutActionName = "Zoom Out"
fitToViewActionName = "Fit to view"
solverSettingsActionName = "Solver.."
saveSettingsActionName = "Save.."
aboutQtActionName = "About Qt.."