#Copyright (C) 2020-2021  Burak Martin (see 'AUTHOR' for full notice)

settingsFileName = ".settings"

brushIconName = "brush"
paintbucketIconName = "bucket"
cropIconName = "crop"
handIconName = "hand"
playIconName = "play"
stopIconName = "stop"
pauseIconName = "pause"
hideIconName = "hide"
showIconName = "show"
undoIconName = "undo"
redoIconName = "redo"
zoomInIconName = "zoom-in"
zoomOutIconName = "zoom-out"
fitInViewIconName = "fit-in-view"
scaleIconName = "scale"
clearTrimapIconName = "erase"
increaseIconName = "increase"
decreaseIconName = "decrease"
removeNewBackgroundIconName = "rm-bg-layer"
fileTreeIconName = "file-tree"
colorBleedingIconName = "color-bleeding"
settingsIconName = "wrench"
